// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDidz9j1vx2_CBY3xEppg009GkHfRD-VXA',
    appId: '1:87971807571:web:806633eab0f53298d861a6',
    messagingSenderId: '87971807571',
    projectId: 'elii-2a822',
    authDomain: 'elii-2a822.firebaseapp.com',
    storageBucket: 'elii-2a822.firebasestorage.app',
    measurementId: 'G-R6F2V77SZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctC4iFmYpsyJUfDsrVoOGEdUwA4cbC6E',
    appId: '1:87971807571:android:760bc808abbd23abd861a6',
    messagingSenderId: '87971807571',
    projectId: 'elii-2a822',
    storageBucket: 'elii-2a822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRJi-zzUamb7nf7VaPJs3Zp8y_hLmbPc',
    appId: '1:87971807571:ios:582760ee91a51759d861a6',
    messagingSenderId: '87971807571',
    projectId: 'elii-2a822',
    storageBucket: 'elii-2a822.firebasestorage.app',
    iosBundleId: 'com.example.komikap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRJi-zzUamb7nf7VaPJs3Zp8y_hLmbPc',
    appId: '1:87971807571:ios:582760ee91a51759d861a6',
    messagingSenderId: '87971807571',
    projectId: 'elii-2a822',
    storageBucket: 'elii-2a822.firebasestorage.app',
    iosBundleId: 'com.example.komikap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDidz9j1vx2_CBY3xEppg009GkHfRD-VXA',
    appId: '1:87971807571:web:71ce036bc3d1c484d861a6',
    messagingSenderId: '87971807571',
    projectId: 'elii-2a822',
    authDomain: 'elii-2a822.firebaseapp.com',
    storageBucket: 'elii-2a822.firebasestorage.app',
    measurementId: 'G-FP0QEHJ0C5',
  );
}
